"""catalog schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-18 20:55:55.842359
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('product','security','company','institution','index','theme')", name=op.f('ck_entity_entity_type')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_entity_record_hash')),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_entity_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'entity_id', name='pk_entity'),
    schema='catalog'
    )
    op.create_index('ix_entity_entity_type', 'entity', ['entity_type'], unique=False, schema='catalog')
    op.create_index('ix_entity_normalized_name_trgm', 'entity', ['normalized_name'], unique=False, schema='catalog', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.create_table('alias',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('alias_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('normalized_alias_text', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("alias_text <> ''", name=op.f('ck_alias_alias_text')),
    sa.CheckConstraint("normalized_alias_text <> ''", name=op.f('ck_alias_normalized_alias_text')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_alias_record_hash')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_alias_valid_dates')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_alias_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_alias_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'alias_id', name='pk_alias'),
    schema='catalog'
    )
    op.create_index('ix_alias_normalized_alias_text', 'alias', ['normalized_alias_text'], unique=False, schema='catalog')
    op.create_index('ix_alias_normalized_alias_text_trgm', 'alias', ['normalized_alias_text'], unique=False, schema='catalog', postgresql_using='gin', postgresql_ops={'normalized_alias_text': 'gin_trgm_ops'})
    op.create_table('identifier',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('identifier_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=False),
    sa.Column('identifier_value', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("identifier_value <> ''", name=op.f('ck_identifier_identifier_value')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_identifier_record_hash')),
    sa.CheckConstraint("scheme <> ''", name=op.f('ck_identifier_scheme')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_identifier_valid_dates')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_identifier_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_identifier_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'identifier_id', name='pk_identifier'),
    schema='catalog'
    )
    op.create_index('ix_identifier_dataset_scheme_value', 'identifier', ['dataset_version', 'scheme', 'identifier_value'], unique=False, schema='catalog')
    op.create_index('uq_identifier_dataset_scheme_value', 'identifier', ['dataset_version', 'scheme', 'identifier_value'], unique=True, schema='catalog')
    op.create_index('uq_identifier_primary_per_entity_scheme', 'identifier', ['dataset_version', 'entity_id', 'scheme'], unique=True, schema='catalog', postgresql_where=sa.text('is_primary IS true'))
    op.create_table('institution',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('institution_kind', sa.Text(), nullable=False),
    sa.CheckConstraint("institution_kind <> ''", name=op.f('ck_institution_institution_kind')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_institution_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_institution_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'entity_id', name='pk_institution'),
    schema='catalog'
    )
    op.create_table('product',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('product_family', sa.Text(), nullable=False),
    sa.Column('primary_currency', sa.Text(), nullable=True),
    sa.CheckConstraint("product_family IN ('domestic_bond','domestic_etf','overseas_etf','public_fund')", name=op.f('ck_product_product_family')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_product_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_product_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'entity_id', name='pk_product'),
    schema='catalog'
    )
    op.create_index('ix_product_product_family', 'product', ['product_family'], unique=False, schema='catalog')
    op.create_table('security',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('security_kind', sa.Text(), nullable=False),
    sa.Column('ticker_display', sa.Text(), nullable=True),
    sa.Column('isin_display', sa.Text(), nullable=True),
    sa.CheckConstraint("security_kind <> ''", name=op.f('ck_security_security_kind')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_security_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_security_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'entity_id', name='pk_security'),
    schema='catalog'
    )
    # ### end Alembic commands ###

    for table in (
        "entity",
        "product",
        "security",
        "institution",
        "identifier",
        "alias",
    ):
        op.execute(f'ALTER TABLE catalog."{table}" OWNER TO fa_migration')
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_nonbuilding_mutation
            BEFORE INSERT OR UPDATE OR DELETE ON catalog.{table}
            FOR EACH ROW
            EXECUTE FUNCTION operations.reject_nonbuilding_dataset_mutation()
            """
        )

    op.execute(
        """
        CREATE FUNCTION catalog.validate_entity_subtype()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, catalog, operations, pg_temp
        AS $function$
        DECLARE
            expected_entity_type text;
            actual_entity_type text;
        BEGIN
            IF TG_TABLE_NAME = 'entity' THEN
                IF EXISTS (
                    SELECT 1
                    FROM catalog.product AS product
                    WHERE product.dataset_version = NEW.dataset_version
                      AND product.entity_id = NEW.entity_id
                      AND NEW.entity_type <> 'product'
                ) OR EXISTS (
                    SELECT 1
                    FROM catalog.security AS security
                    WHERE security.dataset_version = NEW.dataset_version
                      AND security.entity_id = NEW.entity_id
                      AND NEW.entity_type <> 'security'
                ) OR EXISTS (
                    SELECT 1
                    FROM catalog.institution AS institution
                    WHERE institution.dataset_version = NEW.dataset_version
                      AND institution.entity_id = NEW.entity_id
                      AND NEW.entity_type <> 'institution'
                ) THEN
                    RAISE EXCEPTION 'ENTITY_SUBTYPE_MISMATCH'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END IF;

            expected_entity_type := CASE TG_TABLE_NAME
                WHEN 'product' THEN 'product'
                WHEN 'security' THEN 'security'
                WHEN 'institution' THEN 'institution'
            END;
            SELECT entity.entity_type
              INTO actual_entity_type
              FROM catalog.entity AS entity
             WHERE entity.dataset_version = NEW.dataset_version
               AND entity.entity_id = NEW.entity_id
             FOR KEY SHARE;
            IF actual_entity_type IS DISTINCT FROM expected_entity_type THEN
                RAISE EXCEPTION 'ENTITY_SUBTYPE_MISMATCH'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER validate_entity_subtypes
        AFTER INSERT OR UPDATE OF entity_type ON catalog.entity
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION catalog.validate_entity_subtype()
        """
    )
    for table in ("product", "security", "institution"):
        op.execute(
            f"""
            CREATE CONSTRAINT TRIGGER validate_{table}_entity_type
            AFTER INSERT OR UPDATE OF dataset_version, entity_id ON catalog.{table}
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION catalog.validate_entity_subtype()
            """
        )

    op.execute(
        "ALTER FUNCTION catalog.validate_entity_subtype() OWNER TO fa_migration"
    )
    op.execute(
        "REVOKE ALL ON FUNCTION catalog.validate_entity_subtype() "
        "FROM PUBLIC, fa_build, fa_runtime"
    )
    op.execute(
        "REVOKE ALL ON ALL TABLES IN SCHEMA catalog "
        "FROM PUBLIC, fa_build, fa_runtime"
    )
    op.execute("GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO fa_build, fa_runtime")
    op.execute(
        "GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalog TO fa_build"
    )


def downgrade() -> None:
    for table in ("product", "security", "institution"):
        op.execute(
            f"DROP TRIGGER IF EXISTS validate_{table}_entity_type "
            f"ON catalog.{table}"
        )
    op.execute(
        "DROP TRIGGER IF EXISTS validate_entity_subtypes ON catalog.entity"
    )
    for table in (
        "entity",
        "product",
        "security",
        "institution",
        "identifier",
        "alias",
    ):
        op.execute(
            f"DROP TRIGGER IF EXISTS reject_{table}_nonbuilding_mutation "
            f"ON catalog.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS catalog.validate_entity_subtype()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security', schema='catalog')
    op.drop_index('ix_product_product_family', table_name='product', schema='catalog')
    op.drop_table('product', schema='catalog')
    op.drop_table('institution', schema='catalog')
    op.drop_index('uq_identifier_primary_per_entity_scheme', table_name='identifier', schema='catalog', postgresql_where=sa.text('is_primary IS true'))
    op.drop_index('uq_identifier_dataset_scheme_value', table_name='identifier', schema='catalog')
    op.drop_index('ix_identifier_dataset_scheme_value', table_name='identifier', schema='catalog')
    op.drop_table('identifier', schema='catalog')
    op.drop_index('ix_alias_normalized_alias_text_trgm', table_name='alias', schema='catalog', postgresql_using='gin', postgresql_ops={'normalized_alias_text': 'gin_trgm_ops'})
    op.drop_index('ix_alias_normalized_alias_text', table_name='alias', schema='catalog')
    op.drop_table('alias', schema='catalog')
    op.drop_index('ix_entity_normalized_name_trgm', table_name='entity', schema='catalog', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.drop_index('ix_entity_entity_type', table_name='entity', schema='catalog')
    op.drop_table('entity', schema='catalog')
    # ### end Alembic commands ###
