"""fact document search schemas

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-18 21:33:56.228132
"""

from collections.abc import Sequence
from typing import Any

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


class CDBAdminVector(Vector):
    """Render the NCP-managed pgvector type with its owning schema."""

    cache_ok = True

    def get_col_spec(self, **kw: Any) -> str:
        if self.dim is None:
            return "cdb_admin.vector"
        return f"cdb_admin.vector({self.dim})"


revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definition',
    sa.Column('metric_id', sa.Text(), nullable=False),
    sa.Column('definition_version', sa.Text(), nullable=False),
    sa.Column('semantic_family', sa.Text(), nullable=False),
    sa.Column('value_kind', sa.Text(), nullable=False),
    sa.Column('default_unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("definition_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_metric_definition_definition_hash')),
    sa.CheckConstraint("definition_version <> ''", name=op.f('ck_metric_definition_definition_version')),
    sa.CheckConstraint("metric_id <> ''", name=op.f('ck_metric_definition_metric_id')),
    sa.CheckConstraint("semantic_family <> ''", name=op.f('ck_metric_definition_semantic_family')),
    sa.CheckConstraint("value_kind IN ('numeric','text','boolean','date','timestamp')", name=op.f('ck_metric_definition_value_kind')),
    sa.PrimaryKeyConstraint('metric_id', 'definition_version', name='pk_metric_definition'),
    schema='observation'
    )
    op.create_table('embedding_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.Text(), nullable=False),
    sa.Column('approval_record_id', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('model_hash', sa.CHAR(length=64), nullable=False),
    sa.CheckConstraint("approval_record_id <> ''", name=op.f('ck_embedding_model_approval_record_id')),
    sa.CheckConstraint("distance_metric IN ('cosine','inner_product','l2')", name=op.f('ck_embedding_model_distance_metric')),
    sa.CheckConstraint("model_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_embedding_model_model_hash')),
    sa.CheckConstraint("model_id <> ''", name=op.f('ck_embedding_model_model_id')),
    sa.CheckConstraint("model_version <> ''", name=op.f('ck_embedding_model_model_version')),
    sa.CheckConstraint('dimension > 0', name=op.f('ck_embedding_model_dimension')),
    sa.PrimaryKeyConstraint('model_id', 'model_version', name='pk_embedding_model'),
    schema='search'
    )
    op.create_table('relation_record',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('relation_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('predicate_id', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("predicate_id <> ''", name=op.f('ck_relation_record_predicate_id')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_relation_record_record_hash')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_relation_record_valid_dates')),
    sa.ForeignKeyConstraint(['dataset_version', 'object_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_relation_record_object', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'subject_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_relation_record_subject', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_relation_record_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'relation_id', name='pk_relation_record'),
    schema='relation'
    )
    op.create_index('ix_relation_record_lookup', 'relation_record', ['dataset_version', 'predicate_id', 'subject_id', 'object_id'], unique=False, schema='relation')
    op.create_table('source_record',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('publisher_type', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('authority_tier', sa.Text(), nullable=False),
    sa.Column('source_locator_root', sa.Text(), nullable=False),
    sa.Column('content_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('license_or_usage_note', sa.Text(), nullable=True),
    sa.Column('eligible_for_claim', sa.Boolean(), nullable=False),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("authority_tier <> ''", name=op.f('ck_source_record_authority_tier')),
    sa.CheckConstraint("content_checksum ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_record_content_checksum')),
    sa.CheckConstraint("publisher_type <> ''", name=op.f('ck_source_record_publisher_type')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_source_record_record_hash')),
    sa.CheckConstraint("source_locator_root <> ''", name=op.f('ck_source_record_source_locator_root')),
    sa.CheckConstraint("source_title <> ''", name=op.f('ck_source_record_source_title')),
    sa.CheckConstraint("source_type <> ''", name=op.f('ck_source_record_source_type')),
    sa.ForeignKeyConstraint(['dataset_version', 'publisher'], ['catalog.institution.dataset_version', 'catalog.institution.entity_id'], name='fk_source_record_publisher', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_source_record_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'source_id', name='pk_source_record'),
    schema='evidence'
    )
    op.create_table('observation_record',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('observation_id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('relation_id', sa.Text(), nullable=True),
    sa.Column('metric_id', sa.Text(), nullable=False),
    sa.Column('metric_definition_version', sa.Text(), nullable=False),
    sa.Column('value_status', sa.Text(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=38, scale=12), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('timestamp_value', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('applicable_date', sa.Date(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('vintage_date', sa.Date(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(value_status = 'present'  AND num_nonnulls(numeric_value, text_value, boolean_value, date_value, timestamp_value) = 1  AND (numeric_value IS NULL OR numeric_value <> 0)  AND reason_code IS NULL) OR (value_status = 'zero' AND numeric_value = 0  AND text_value IS NULL AND boolean_value IS NULL  AND date_value IS NULL AND timestamp_value IS NULL  AND reason_code IS NULL) OR (value_status IN ('missing','placeholder','unavailable','inapplicable','unknown')  AND num_nonnulls(numeric_value, text_value, boolean_value, date_value, timestamp_value) = 0  AND reason_code IS NOT NULL AND reason_code <> '')", name=op.f('ck_observation_record_typed_value_status')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_observation_record_record_hash')),
    sa.CheckConstraint("value_status IN ('present','zero','missing','placeholder','unavailable','inapplicable','unknown')", name=op.f('ck_observation_record_value_status')),
    sa.CheckConstraint('(entity_id IS NOT NULL) <> (relation_id IS NOT NULL)', name=op.f('ck_observation_record_target_xor')),
    sa.CheckConstraint('period_end IS NULL OR period_start IS NULL OR period_end >= period_start', name=op.f('ck_observation_record_period_dates')),
    sa.ForeignKeyConstraint(['dataset_version', 'entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_observation_record_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'relation_id'], ['relation.relation_record.dataset_version', 'relation.relation_record.relation_id'], name='fk_observation_record_relation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_observation_record_dataset_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metric_id', 'metric_definition_version'], ['observation.metric_definition.metric_id', 'observation.metric_definition.definition_version'], name='fk_observation_record_metric_definition', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'observation_id', name='pk_observation_record'),
    schema='observation'
    )
    op.create_index('ix_observation_record_entity_metric_date', 'observation_record', ['dataset_version', 'entity_id', 'metric_id', 'applicable_date'], unique=False, schema='observation')
    op.create_index('ix_observation_record_relation_metric_date', 'observation_record', ['dataset_version', 'relation_id', 'metric_id', 'applicable_date'], unique=False, schema='observation')
    op.create_table('document_record',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('content_checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("content_checksum ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_record_content_checksum')),
    sa.CheckConstraint("document_title <> ''", name=op.f('ck_document_record_document_title')),
    sa.CheckConstraint("document_type <> ''", name=op.f('ck_document_record_document_type')),
    sa.CheckConstraint("object_key <> ''", name=op.f('ck_document_record_object_key')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_record_record_hash')),
    sa.ForeignKeyConstraint(['dataset_version', 'source_id'], ['evidence.source_record.dataset_version', 'evidence.source_record.source_id'], name='fk_document_record_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_document_record_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'document_id', name='pk_document_record'),
    schema='document'
    )
    op.create_index('ix_document_record_source', 'document_record', ['dataset_version', 'source_id'], unique=False, schema='document')
    op.create_table('document_chunk',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('parent_chunk_id', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('sentence_start', sa.Integer(), nullable=True),
    sa.Column('sentence_end', sa.Integer(), nullable=True),
    sa.Column('exact_text', sa.Text(), nullable=False),
    sa.Column('normalized_search_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_chunk_content_hash')),
    sa.CheckConstraint("exact_text <> ''", name=op.f('ck_document_chunk_exact_text')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_chunk_record_hash')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_document_chunk_ordinal')),
    sa.CheckConstraint('page_end IS NULL OR (page_start IS NOT NULL AND page_end >= page_start)', name=op.f('ck_document_chunk_page_range')),
    sa.CheckConstraint('page_start IS NULL OR page_start >= 1', name=op.f('ck_document_chunk_page_start')),
    sa.CheckConstraint('sentence_end IS NULL OR (sentence_start IS NOT NULL AND sentence_end >= sentence_start)', name=op.f('ck_document_chunk_sentence_range')),
    sa.CheckConstraint('sentence_start IS NULL OR sentence_start >= 0', name=op.f('ck_document_chunk_sentence_start')),
    sa.ForeignKeyConstraint(['dataset_version', 'document_id', 'parent_chunk_id'], ['document.document_chunk.dataset_version', 'document.document_chunk.document_id', 'document.document_chunk.chunk_id'], name='fk_document_chunk_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'document_id'], ['document.document_record.dataset_version', 'document.document_record.document_id'], name='fk_document_chunk_document', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_document_chunk_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'chunk_id', name='pk_document_chunk'),
    sa.UniqueConstraint('dataset_version', 'document_id', 'chunk_id', 'content_hash', name='uq_document_chunk_exact_content'),
    sa.UniqueConstraint('dataset_version', 'document_id', 'chunk_id', name='uq_document_chunk_document_chunk'),
    sa.UniqueConstraint('dataset_version', 'document_id', 'ordinal', name='uq_document_chunk_ordinal'),
    schema='document'
    )
    op.create_index('ix_document_chunk_normalized_search_text_trgm', 'document_chunk', ['normalized_search_text'], unique=False, schema='document', postgresql_using='gin', postgresql_ops={'normalized_search_text': 'gin_trgm_ops'})
    op.create_table('document_embedding',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('chunk_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', CDBAdminVector(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("chunk_content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_embedding_chunk_content_hash')),
    sa.CheckConstraint('dimension > 0', name=op.f('ck_document_embedding_dimension')),
    sa.ForeignKeyConstraint(['dataset_version', 'document_id', 'chunk_id', 'chunk_content_hash'], ['document.document_chunk.dataset_version', 'document.document_chunk.document_id', 'document.document_chunk.chunk_id', 'document.document_chunk.content_hash'], name='fk_document_embedding_exact_chunk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_document_embedding_dataset_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id', 'model_version'], ['search.embedding_model.model_id', 'search.embedding_model.model_version'], name='fk_document_embedding_model', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'embedding_id', name='pk_document_embedding'),
    schema='search'
    )
    op.create_index('ix_document_embedding_chunk', 'document_embedding', ['dataset_version', 'document_id', 'chunk_id'], unique=False, schema='search')
    op.create_index('ix_document_embedding_model', 'document_embedding', ['model_id', 'model_version'], unique=False, schema='search')
    # ### end Alembic commands ###

    table_schemas = {
        "relation_record": "relation",
        "metric_definition": "observation",
        "observation_record": "observation",
        "source_record": "evidence",
        "document_record": "document",
        "document_chunk": "document",
        "embedding_model": "search",
        "document_embedding": "search",
    }
    for table, schema in table_schemas.items():
        op.execute(f'ALTER TABLE {schema}."{table}" OWNER TO fa_migration')

    for table, schema in (
        ("relation_record", "relation"),
        ("observation_record", "observation"),
        ("document_record", "document"),
        ("document_chunk", "document"),
        ("document_embedding", "search"),
    ):
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_nonbuilding_mutation
            BEFORE INSERT OR UPDATE OR DELETE ON {schema}.{table}
            FOR EACH ROW
            EXECUTE FUNCTION operations.reject_nonbuilding_dataset_mutation()
            """
        )

    op.execute(
        """
        CREATE TRIGGER reject_source_record_nonbuilding_insert
        BEFORE INSERT ON evidence.source_record
        FOR EACH ROW
        EXECUTE FUNCTION operations.reject_nonbuilding_dataset_mutation()
        """
    )
    for table, schema in (
        ("source_record", "evidence"),
        ("metric_definition", "observation"),
        ("embedding_model", "search"),
    ):
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_mutation
            BEFORE UPDATE OR DELETE ON {schema}.{table}
            FOR EACH ROW
            EXECUTE FUNCTION operations.reject_immutable_mutation()
            """
        )

    op.execute(
        """
        CREATE FUNCTION observation.validate_metric_value_kind()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, observation, pg_temp
        AS $function$
        DECLARE
            registered_value_kind text;
            stored_value_kind text;
        BEGIN
            SELECT metric.value_kind
              INTO registered_value_kind
              FROM observation.metric_definition AS metric
             WHERE metric.metric_id = NEW.metric_id
               AND metric.definition_version = NEW.metric_definition_version
             FOR KEY SHARE;

            stored_value_kind := CASE
                WHEN NEW.numeric_value IS NOT NULL THEN 'numeric'
                WHEN NEW.text_value IS NOT NULL THEN 'text'
                WHEN NEW.boolean_value IS NOT NULL THEN 'boolean'
                WHEN NEW.date_value IS NOT NULL THEN 'date'
                WHEN NEW.timestamp_value IS NOT NULL THEN 'timestamp'
                ELSE NULL
            END;
            IF NEW.value_status = 'zero' THEN
                stored_value_kind := 'numeric';
            END IF;
            IF stored_value_kind IS NOT NULL
               AND stored_value_kind IS DISTINCT FROM registered_value_kind THEN
                RAISE EXCEPTION 'METRIC_VALUE_KIND_MISMATCH'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER validate_metric_value_kind
        AFTER INSERT OR UPDATE OF metric_id, metric_definition_version,
            value_status, numeric_value, text_value, boolean_value,
            date_value, timestamp_value
        ON observation.observation_record
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION observation.validate_metric_value_kind()
        """
    )

    op.execute(
        """
        CREATE FUNCTION evidence.validate_source_publisher_type()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, catalog, pg_temp
        AS $function$
        DECLARE
            publisher_entity_type text;
        BEGIN
            SELECT entity.entity_type
              INTO publisher_entity_type
              FROM catalog.entity AS entity
             WHERE entity.dataset_version = NEW.dataset_version
               AND entity.entity_id = NEW.publisher
             FOR KEY SHARE;
            IF publisher_entity_type IS DISTINCT FROM 'institution' THEN
                RAISE EXCEPTION 'SOURCE_PUBLISHER_NOT_INSTITUTION'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER validate_source_publisher_type
        AFTER INSERT OR UPDATE OF dataset_version, publisher
        ON evidence.source_record
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION evidence.validate_source_publisher_type()
        """
    )

    op.execute(
        """
        CREATE FUNCTION search.validate_document_embedding()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, search, cdb_admin, pg_temp
        AS $function$
        DECLARE
            registered_dimension integer;
            actual_dimension integer;
        BEGIN
            SELECT model.dimension
              INTO registered_dimension
              FROM search.embedding_model AS model
             WHERE model.model_id = NEW.model_id
               AND model.model_version = NEW.model_version
             FOR KEY SHARE;
            actual_dimension := cdb_admin.vector_dims(NEW.embedding);
            IF NEW.dimension IS DISTINCT FROM actual_dimension
               OR NEW.dimension IS DISTINCT FROM registered_dimension THEN
                RAISE EXCEPTION 'EMBEDDING_DIMENSION_MISMATCH'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER validate_document_embedding
        AFTER INSERT OR UPDATE OF model_id, model_version, dimension, embedding
        ON search.document_embedding
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION search.validate_document_embedding()
        """
    )

    protected_functions = (
        ("observation", "validate_metric_value_kind()"),
        ("evidence", "validate_source_publisher_type()"),
        ("search", "validate_document_embedding()"),
    )
    for schema, signature in protected_functions:
        op.execute(f"ALTER FUNCTION {schema}.{signature} OWNER TO fa_migration")
        op.execute(
            f"REVOKE ALL ON FUNCTION {schema}.{signature} "
            "FROM PUBLIC, fa_build, fa_runtime"
        )

    for schema in ("relation", "observation", "document", "search", "evidence"):
        op.execute(
            f"REVOKE ALL ON ALL TABLES IN SCHEMA {schema} "
            "FROM PUBLIC, fa_build, fa_runtime"
        )
    op.execute(
        "GRANT SELECT ON ALL TABLES IN SCHEMA relation, observation, document, "
        "search, evidence TO fa_build, fa_runtime"
    )
    op.execute(
        "GRANT INSERT, UPDATE, DELETE ON relation.relation_record, "
        "observation.observation_record, document.document_record, "
        "document.document_chunk, search.document_embedding TO fa_build"
    )
    op.execute(
        "GRANT INSERT ON observation.metric_definition, search.embedding_model, "
        "evidence.source_record TO fa_build"
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS validate_document_embedding "
        "ON search.document_embedding"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS validate_source_publisher_type "
        "ON evidence.source_record"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS validate_metric_value_kind "
        "ON observation.observation_record"
    )
    for table, schema in (
        ("relation_record", "relation"),
        ("observation_record", "observation"),
        ("document_record", "document"),
        ("document_chunk", "document"),
        ("document_embedding", "search"),
    ):
        op.execute(
            f"DROP TRIGGER IF EXISTS reject_{table}_nonbuilding_mutation "
            f"ON {schema}.{table}"
        )
    op.execute(
        "DROP TRIGGER IF EXISTS reject_source_record_nonbuilding_insert "
        "ON evidence.source_record"
    )
    for table, schema in (
        ("source_record", "evidence"),
        ("metric_definition", "observation"),
        ("embedding_model", "search"),
    ):
        op.execute(
            f"DROP TRIGGER IF EXISTS reject_{table}_mutation ON {schema}.{table}"
        )
    op.execute("DROP FUNCTION IF EXISTS search.validate_document_embedding()")
    op.execute("DROP FUNCTION IF EXISTS evidence.validate_source_publisher_type()")
    op.execute("DROP FUNCTION IF EXISTS observation.validate_metric_value_kind()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_embedding_model', table_name='document_embedding', schema='search')
    op.drop_index('ix_document_embedding_chunk', table_name='document_embedding', schema='search')
    op.drop_table('document_embedding', schema='search')
    op.drop_index('ix_document_chunk_normalized_search_text_trgm', table_name='document_chunk', schema='document', postgresql_using='gin', postgresql_ops={'normalized_search_text': 'gin_trgm_ops'})
    op.drop_table('document_chunk', schema='document')
    op.drop_index('ix_document_record_source', table_name='document_record', schema='document')
    op.drop_table('document_record', schema='document')
    op.drop_index('ix_observation_record_relation_metric_date', table_name='observation_record', schema='observation')
    op.drop_index('ix_observation_record_entity_metric_date', table_name='observation_record', schema='observation')
    op.drop_table('observation_record', schema='observation')
    op.drop_table('source_record', schema='evidence')
    op.drop_index('ix_relation_record_lookup', table_name='relation_record', schema='relation')
    op.drop_table('relation_record', schema='relation')
    op.drop_table('embedding_model', schema='search')
    op.drop_table('metric_definition', schema='observation')
    # ### end Alembic commands ###
