"""evidence ledger

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-18 22:19:35.028491
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        r"""
        CREATE FUNCTION evidence.is_valid_tagged_value(candidate jsonb)
        RETURNS boolean
        LANGUAGE plpgsql
        IMMUTABLE
        STRICT
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        DECLARE
            tag text;
            value_type text;
            item jsonb;
            key_count integer;
            value_text text;
        BEGIN
            IF jsonb_typeof(candidate) IS DISTINCT FROM 'object' THEN
                RETURN false;
            END IF;
            SELECT count(*) INTO key_count
              FROM jsonb_object_keys(candidate);
            tag := candidate ->> 'type';

            IF tag = 'tuple' THEN
                IF key_count <> 2
                   OR NOT candidate ?& ARRAY['type', 'items']
                   OR jsonb_typeof(candidate -> 'items') IS DISTINCT FROM 'array'
                THEN
                    RETURN false;
                END IF;
                FOR item IN SELECT value FROM jsonb_array_elements(candidate -> 'items')
                LOOP
                    IF item ->> 'type' = 'tuple'
                       OR NOT evidence.is_valid_tagged_value(item)
                    THEN
                        RETURN false;
                    END IF;
                END LOOP;
                RETURN true;
            END IF;

            IF key_count <> 2 OR NOT candidate ?& ARRAY['type', 'value'] THEN
                RETURN false;
            END IF;
            value_type := jsonb_typeof(candidate -> 'value');
            value_text := candidate ->> 'value';

            IF tag = 'null' THEN
                RETURN value_type = 'null';
            ELSIF tag = 'string' THEN
                RETURN value_type = 'string';
            ELSIF tag = 'integer' THEN
                RETURN value_type = 'number'
                   AND (candidate -> 'value')::text ~ '^(0|-?[1-9][0-9]*)$';
            ELSIF tag = 'decimal' THEN
                RETURN value_type = 'string'
                   AND value_text ~ '^(0|-?[1-9][0-9]*|-?(0|[1-9][0-9]*)\.[0-9]*[1-9])$';
            ELSIF tag = 'boolean' THEN
                RETURN value_type = 'boolean';
            ELSIF tag = 'date' THEN
                IF value_type <> 'string'
                   OR value_text !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
                THEN
                    RETURN false;
                END IF;
                PERFORM value_text::date;
                RETURN true;
            ELSIF tag = 'datetime' THEN
                IF value_type <> 'string'
                   OR value_text !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,6})?Z$'
                THEN
                    RETURN false;
                END IF;
                PERFORM value_text::timestamptz;
                RETURN true;
            END IF;
            RETURN false;
        EXCEPTION
            WHEN datetime_field_overflow OR invalid_datetime_format THEN
                RETURN false;
        END
        $function$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_record',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('evidence_kind', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('predicate_id', sa.Text(), nullable=True),
    sa.Column('value_or_object_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('applicable_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('vintage_date', sa.Date(), nullable=True),
    sa.Column('locator_type', sa.Text(), nullable=False),
    sa.Column('locator_uri_or_object_key', sa.Text(), nullable=False),
    sa.Column('locator_record_key', sa.Text(), nullable=True),
    sa.Column('locator_sheet', sa.Text(), nullable=True),
    sa.Column('locator_row', sa.Integer(), nullable=True),
    sa.Column('locator_column', sa.Text(), nullable=True),
    sa.Column('locator_page', sa.Integer(), nullable=True),
    sa.Column('locator_section', sa.Text(), nullable=True),
    sa.Column('locator_sentence_start', sa.Integer(), nullable=True),
    sa.Column('locator_sentence_end', sa.Integer(), nullable=True),
    sa.Column('raw_value_repr', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('mapping_version', sa.Text(), nullable=False),
    sa.Column('cutoff_status', sa.Text(), nullable=False),
    sa.Column('record_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('scope_completeness', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(evidence_kind = 'query_scope' AND scope_completeness IS NOT NULL AND scope_completeness IN ('closed_world','bounded_unknown')) OR (evidence_kind <> 'query_scope' AND scope_completeness IS NULL)", name=op.f('ck_evidence_record_scope_completeness')),
    sa.CheckConstraint("cutoff_status IN ('eligible','after_cutoff','unknown_vintage','inapplicable')", name=op.f('ck_evidence_record_cutoff_status')),
    sa.CheckConstraint("evidence.is_valid_tagged_value(normalized_value) AND normalized_value ->> 'type' <> 'tuple'", name=op.f('ck_evidence_record_normalized_value')),
    sa.CheckConstraint("evidence.is_valid_tagged_value(value_or_object_id) AND value_or_object_id ->> 'type' <> 'tuple'", name=op.f('ck_evidence_record_value_or_object_id')),
    sa.CheckConstraint("evidence_kind IN ('observation','relation','document_span','query_scope','exclusion','policy')", name=op.f('ck_evidence_record_evidence_kind')),
    sa.CheckConstraint("evidence_kind NOT IN ('observation','relation','document_span') OR subject_id IS NOT NULL", name=op.f('ck_evidence_record_origin_subject')),
    sa.CheckConstraint("record_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_evidence_record_record_hash')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_evidence_record_valid_dates')),
    sa.ForeignKeyConstraint(['dataset_version', 'source_id'], ['evidence.source_record.dataset_version', 'evidence.source_record.source_id'], name='fk_evidence_record_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'subject_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_evidence_record_subject', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version'], ['operations.dataset_version.dataset_version'], name='fk_evidence_record_dataset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'evidence_id', name='pk_evidence_record'),
    schema='evidence'
    )
    op.create_index('ix_evidence_record_eligible_cutoff', 'evidence_record', ['dataset_version', 'cutoff_status'], unique=False, schema='evidence', postgresql_where=sa.text("cutoff_status = 'eligible'"))
    op.create_index('ix_evidence_record_source', 'evidence_record', ['dataset_version', 'source_id'], unique=False, schema='evidence')
    op.create_index('ix_evidence_record_subject_predicate_date', 'evidence_record', ['dataset_version', 'subject_id', 'predicate_id', sa.literal_column('applicable_date DESC')], unique=False, schema='evidence')
    op.create_table('evidence_observation_origin',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('observation_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_evidence_observation_origin_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'observation_id'], ['observation.observation_record.dataset_version', 'observation.observation_record.observation_id'], name='fk_evidence_observation_origin_observation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'evidence_id', name='pk_evidence_observation_origin'),
    schema='evidence'
    )
    op.create_table('evidence_relation_origin',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('relation_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_evidence_relation_origin_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'relation_id'], ['relation.relation_record.dataset_version', 'relation.relation_record.relation_id'], name='fk_evidence_relation_origin_relation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'evidence_id', name='pk_evidence_relation_origin'),
    schema='evidence'
    )
    op.create_table('evidence_document_origin',
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version', 'chunk_id'], ['document.document_chunk.dataset_version', 'document.document_chunk.chunk_id'], name='fk_evidence_document_origin_chunk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_evidence_document_origin_evidence', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_version', 'evidence_id', name='pk_evidence_document_origin'),
    schema='evidence'
    )
    op.create_unique_constraint('uq_request_run_run_dataset', 'request_run', ['run_id', 'dataset_version'], schema='operations')
    op.create_table('calculation_record',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('calculation_type', sa.Text(), nullable=False),
    sa.Column('formula_id', sa.Text(), nullable=False),
    sa.Column('formula_version', sa.Text(), nullable=False),
    sa.Column('tie_break_rule', sa.Text(), nullable=True),
    sa.Column('result_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('rounding_rule', sa.Text(), nullable=True),
    sa.Column('calculation_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("calculation_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_calculation_record_calculation_hash')),
    sa.CheckConstraint("calculation_type IN ('conversion','return','ranking','aggregation','comparison','similarity')", name=op.f('ck_calculation_record_calculation_type')),
    sa.CheckConstraint("evidence.is_valid_tagged_value(result_value) AND result_value ->> 'type' <> 'tuple'", name=op.f('ck_calculation_record_result_value')),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version'], ['operations.request_run.run_id', 'operations.request_run.dataset_version'], name='fk_calculation_record_request_dataset', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', name='pk_calculation_record'),
    sa.UniqueConstraint('run_id', 'dataset_version', 'calculation_id', name='uq_calculation_record_run_dataset_calculation'),
    schema='evidence'
    )
    op.create_index('ix_calculation_record_run_hash', 'calculation_record', ['run_id', 'calculation_hash'], unique=False, schema='evidence')
    op.create_table('atomic_claim',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=False),
    sa.Column('subtask_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('subject_kind', sa.Text(), nullable=False),
    sa.Column('subject_entity_id', sa.Text(), nullable=True),
    sa.Column('request_subject_id', sa.Text(), nullable=True),
    sa.Column('predicate_id', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('display_policy_id', sa.Text(), nullable=False),
    sa.Column('claim_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(claim_type IN ('direct_fact','relation','derived_metric','rank','similarity') AND subject_kind = 'entity' AND subject_entity_id IS NOT NULL AND subject_entity_id = subject_id AND request_subject_id IS NULL) OR (claim_type IN ('no_match','data_limitation','policy_boundary') AND subject_kind = 'request' AND subject_entity_id IS NULL AND request_subject_id IS NOT NULL AND request_subject_id = subject_id AND subject_id = subtask_id)", name=op.f('ck_atomic_claim_subject_scope')),
    sa.CheckConstraint("(num_nonnulls(object_id, value) = 1) OR (claim_type IN ('data_limitation','policy_boundary') AND object_id IS NULL AND value IS NULL)", name=op.f('ck_atomic_claim_target')),
    sa.CheckConstraint("claim_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_atomic_claim_claim_hash')),
    sa.CheckConstraint("claim_type IN ('direct_fact','relation','derived_metric','rank','similarity','no_match','data_limitation','policy_boundary')", name=op.f('ck_atomic_claim_claim_type')),
    sa.CheckConstraint("value IS NULL OR (evidence.is_valid_tagged_value(value) AND value ->> 'type' <> 'tuple')", name=op.f('ck_atomic_claim_value')),
    sa.ForeignKeyConstraint(['dataset_version', 'object_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_atomic_claim_object', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'subject_entity_id'], ['catalog.entity.dataset_version', 'catalog.entity.entity_id'], name='fk_atomic_claim_subject_entity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version'], ['operations.request_run.run_id', 'operations.request_run.dataset_version'], name='fk_atomic_claim_request_dataset', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'request_subject_id'], ['operations.request_subtask.run_id', 'operations.request_subtask.subtask_id'], name='fk_atomic_claim_request_subject', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'subtask_id'], ['operations.request_subtask.run_id', 'operations.request_subtask.subtask_id'], name='fk_atomic_claim_subtask', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'claim_id', name='pk_atomic_claim'),
    sa.UniqueConstraint('run_id', 'dataset_version', 'claim_id', name='uq_atomic_claim_run_dataset_claim'),
    schema='evidence'
    )
    op.create_index('ix_atomic_claim_run_hash', 'atomic_claim', ['run_id', 'claim_hash'], unique=False, schema='evidence')
    op.create_table('calculation_dependency',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('input_calculation_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('calculation_id <> input_calculation_id', name=op.f('ck_calculation_dependency_not_self')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_calculation_dependency_ordinal')),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_dependency_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'input_calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_dependency_input', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', 'ordinal', name='pk_calculation_dependency'),
    sa.UniqueConstraint('run_id', 'calculation_id', 'input_calculation_id', name='uq_calculation_dependency_input'),
    schema='evidence'
    )
    op.create_table('calculation_parameter',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('evidence.is_valid_tagged_value(value)', name=op.f('ck_calculation_parameter_value')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_calculation_parameter_ordinal')),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_parameter_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', 'ordinal', name='pk_calculation_parameter'),
    sa.UniqueConstraint('run_id', 'calculation_id', 'parameter_id', name='uq_calculation_parameter_id'),
    schema='evidence'
    )
    op.create_table('claim_qualifier',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('qualifier_id', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('evidence.is_valid_tagged_value(value)', name=op.f('ck_claim_qualifier_value')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_claim_qualifier_ordinal')),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'claim_id'], ['evidence.atomic_claim.run_id', 'evidence.atomic_claim.dataset_version', 'evidence.atomic_claim.claim_id'], name='fk_claim_qualifier_claim', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'claim_id', 'ordinal', name='pk_claim_qualifier'),
    sa.UniqueConstraint('run_id', 'claim_id', 'qualifier_id', name='uq_claim_qualifier_id'),
    schema='evidence'
    )
    op.create_table('calculation_evidence_input',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_calculation_evidence_input_ordinal')),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_calculation_evidence_input_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_evidence_input_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', 'ordinal', name='pk_calculation_evidence_input'),
    sa.UniqueConstraint('run_id', 'calculation_id', 'evidence_id', name='uq_calculation_evidence_input_evidence'),
    schema='evidence'
    )
    op.create_table('calculation_exclusion',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_calculation_exclusion_ordinal')),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_calculation_exclusion_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_exclusion_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', 'ordinal', name='pk_calculation_exclusion'),
    sa.UniqueConstraint('run_id', 'calculation_id', 'evidence_id', name='uq_calculation_exclusion_evidence'),
    schema='evidence'
    )
    op.create_table('calculation_population',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('population_id', sa.Text(), nullable=False),
    sa.Column('scope_evidence_id', sa.Text(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('population_hash', sa.CHAR(length=64), nullable=False),
    sa.CheckConstraint("population_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_calculation_population_population_hash')),
    sa.CheckConstraint('member_count >= 0', name=op.f('ck_calculation_population_member_count')),
    sa.ForeignKeyConstraint(['dataset_version', 'scope_evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_calculation_population_scope_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_calculation_population_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', name='pk_calculation_population'),
    sa.UniqueConstraint('run_id', 'dataset_version', 'calculation_id', name='uq_calculation_population_run_dataset_calculation'),
    sa.UniqueConstraint('run_id', 'population_id', name='uq_calculation_population_id'),
    schema='evidence'
    )
    op.create_table('claim_support',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('support_kind', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=True),
    sa.Column('calculation_id', sa.Text(), nullable=True),
    sa.Column('support_role', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("(support_kind = 'calculation' AND calculation_id IS NOT NULL AND evidence_id IS NULL) OR (support_kind <> 'calculation' AND evidence_id IS NOT NULL AND calculation_id IS NULL)", name=op.f('ck_claim_support_target')),
    sa.CheckConstraint("support_kind IN ('direct','calculation','scope','exclusion','policy')", name=op.f('ck_claim_support_support_kind')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_claim_support_ordinal')),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_claim_support_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_claim_support_calculation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'claim_id'], ['evidence.atomic_claim.run_id', 'evidence.atomic_claim.dataset_version', 'evidence.atomic_claim.claim_id'], name='fk_claim_support_claim', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'claim_id', 'ordinal', name='pk_claim_support'),
    schema='evidence'
    )
    op.create_index('ix_claim_support_calculation', 'claim_support', ['run_id', 'calculation_id'], unique=False, schema='evidence')
    op.create_index('ix_claim_support_evidence', 'claim_support', ['dataset_version', 'evidence_id'], unique=False, schema='evidence')
    op.create_table('calculation_population_filter',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Text(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_calculation_population_filter_ordinal')),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_population.run_id', 'evidence.calculation_population.dataset_version', 'evidence.calculation_population.calculation_id'], name='fk_calculation_population_filter_population', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'calculation_id', 'ordinal', name='pk_calculation_population_filter'),
    sa.UniqueConstraint('run_id', 'calculation_id', 'filter_id', name='uq_calculation_population_filter_id'),
    schema='evidence'
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION evidence.reject_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        BEGIN
            RAISE EXCEPTION 'IMMUTABLE_EVIDENCE_LEDGER_RECORD'
                USING ERRCODE = '55000';
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE FUNCTION evidence.validate_cutoff_status()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, operations, pg_temp
        AS $function$
        DECLARE
            dataset_cutoff date;
            has_after_cutoff boolean;
        BEGIN
            SELECT dataset.cutoff_date
              INTO dataset_cutoff
              FROM operations.dataset_version AS dataset
             WHERE dataset.dataset_version = NEW.dataset_version
             FOR KEY SHARE;

            IF dataset_cutoff IS NULL THEN
                RETURN NEW;
            END IF;
            has_after_cutoff :=
                COALESCE(NEW.applicable_date > dataset_cutoff, false)
                OR COALESCE(
                    (NEW.published_at AT TIME ZONE 'UTC')::date > dataset_cutoff,
                    false
                )
                OR COALESCE(
                    (NEW.available_at AT TIME ZONE 'UTC')::date > dataset_cutoff,
                    false
                )
                OR COALESCE(NEW.vintage_date > dataset_cutoff, false);

            IF has_after_cutoff AND NEW.cutoff_status <> 'after_cutoff' THEN
                RAISE EXCEPTION 'EVIDENCE_AFTER_CUTOFF_STATUS_REQUIRED'
                    USING ERRCODE = '23514';
            ELSIF NOT has_after_cutoff AND NEW.cutoff_status = 'after_cutoff' THEN
                RAISE EXCEPTION 'EVIDENCE_AFTER_CUTOFF_STATUS_INVALID'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE FUNCTION evidence.validate_evidence_origin()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        DECLARE
            stored_kind text;
            observation_count integer;
            relation_count integer;
            document_count integer;
        BEGIN
            SELECT evidence_kind
              INTO stored_kind
              FROM evidence.evidence_record
             WHERE dataset_version = NEW.dataset_version
               AND evidence_id = NEW.evidence_id;
            IF stored_kind IS NULL THEN
                RETURN NEW;
            END IF;

            SELECT count(*) INTO observation_count
              FROM evidence.evidence_observation_origin
             WHERE dataset_version = NEW.dataset_version
               AND evidence_id = NEW.evidence_id;
            SELECT count(*) INTO relation_count
              FROM evidence.evidence_relation_origin
             WHERE dataset_version = NEW.dataset_version
               AND evidence_id = NEW.evidence_id;
            SELECT count(*) INTO document_count
              FROM evidence.evidence_document_origin
             WHERE dataset_version = NEW.dataset_version
               AND evidence_id = NEW.evidence_id;

            IF NOT (
                (stored_kind = 'observation'
                 AND observation_count = 1
                 AND relation_count = 0 AND document_count = 0)
                OR (stored_kind = 'relation'
                    AND relation_count = 1
                    AND observation_count = 0 AND document_count = 0)
                OR (stored_kind = 'document_span'
                    AND document_count = 1
                    AND observation_count = 0 AND relation_count = 0)
                OR (stored_kind IN ('query_scope','exclusion','policy')
                    AND observation_count = 0
                    AND relation_count = 0 AND document_count = 0)
            ) THEN
                RAISE EXCEPTION 'INVALID_EVIDENCE_ORIGIN'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE FUNCTION evidence.validate_calculation_aggregate()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        DECLARE
            stored_type text;
            stored_tie_break text;
            evidence_input_count integer;
            dependency_count integer;
            population_count integer;
            population_filter_count integer;
        BEGIN
            SELECT calculation_type, tie_break_rule
              INTO stored_type, stored_tie_break
              FROM evidence.calculation_record
             WHERE run_id = NEW.run_id
               AND calculation_id = NEW.calculation_id;
            IF stored_type IS NULL THEN
                RETURN NEW;
            END IF;

            SELECT count(*) INTO evidence_input_count
              FROM evidence.calculation_evidence_input
             WHERE run_id = NEW.run_id
               AND calculation_id = NEW.calculation_id;
            SELECT count(*) INTO dependency_count
              FROM evidence.calculation_dependency
             WHERE run_id = NEW.run_id
               AND calculation_id = NEW.calculation_id;
            SELECT count(*) INTO population_count
              FROM evidence.calculation_population
             WHERE run_id = NEW.run_id
               AND calculation_id = NEW.calculation_id;
            SELECT count(*) INTO population_filter_count
              FROM evidence.calculation_population_filter
             WHERE run_id = NEW.run_id
               AND calculation_id = NEW.calculation_id;

            IF evidence_input_count + dependency_count = 0 THEN
                RAISE EXCEPTION 'CALCULATION_INPUT_REQUIRED'
                    USING ERRCODE = '23514';
            END IF;
            IF stored_type IN ('ranking', 'aggregation')
               AND population_count <> 1 THEN
                RAISE EXCEPTION 'CALCULATION_POPULATION_REQUIRED'
                    USING ERRCODE = '23514';
            END IF;
            IF stored_type = 'ranking'
               AND (population_filter_count = 0 OR stored_tie_break IS NULL) THEN
                RAISE EXCEPTION 'RANKING_METADATA_INCOMPLETE'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE FUNCTION evidence.reject_calculation_cycle()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        BEGIN
            IF EXISTS (
                WITH RECURSIVE dependency_path(calculation_id) AS (
                    SELECT NEW.input_calculation_id
                    UNION
                    SELECT edge.input_calculation_id
                      FROM evidence.calculation_dependency AS edge
                      JOIN dependency_path AS path
                        ON edge.calculation_id = path.calculation_id
                     WHERE edge.run_id = NEW.run_id
                )
                SELECT 1
                  FROM dependency_path
                 WHERE calculation_id = NEW.calculation_id
            ) THEN
                RAISE EXCEPTION 'CALCULATION_CYCLE'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE FUNCTION evidence.validate_claim_aggregate()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, evidence, pg_temp
        AS $function$
        DECLARE
            stored_type text;
            has_target boolean;
            qualifier_count integer;
            support_count integer;
        BEGIN
            SELECT claim_type, num_nonnulls(object_id, value) = 1
              INTO stored_type, has_target
              FROM evidence.atomic_claim
             WHERE run_id = NEW.run_id
               AND claim_id = NEW.claim_id;
            IF stored_type IS NULL THEN
                RETURN NEW;
            END IF;
            SELECT count(*) INTO qualifier_count
              FROM evidence.claim_qualifier
             WHERE run_id = NEW.run_id AND claim_id = NEW.claim_id;
            SELECT count(*) INTO support_count
              FROM evidence.claim_support
             WHERE run_id = NEW.run_id AND claim_id = NEW.claim_id;

            IF support_count = 0 THEN
                RAISE EXCEPTION 'CLAIM_SUPPORT_REQUIRED'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT has_target
               AND (stored_type NOT IN ('data_limitation','policy_boundary')
                    OR qualifier_count = 0) THEN
                RAISE EXCEPTION 'QUALIFIER_ONLY_CLAIM_INVALID'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $function$
        """
    )

    op.execute(
        """
        CREATE TRIGGER validate_cutoff_status
        BEFORE INSERT OR UPDATE OF dataset_version, applicable_date,
            published_at, available_at, vintage_date, cutoff_status
        ON evidence.evidence_record
        FOR EACH ROW
        EXECUTE FUNCTION evidence.validate_cutoff_status()
        """
    )
    for table in (
        "evidence_record",
        "evidence_observation_origin",
        "evidence_relation_origin",
        "evidence_document_origin",
    ):
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_mutation
            BEFORE UPDATE OR DELETE ON evidence.{table}
            FOR EACH ROW
            EXECUTE FUNCTION evidence.reject_mutation()
            """
        )
        op.execute(
            f"""
            CREATE CONSTRAINT TRIGGER validate_{table}_origin
            AFTER INSERT ON evidence.{table}
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION evidence.validate_evidence_origin()
            """
        )

    for table in (
        "calculation_record",
        "calculation_parameter",
        "calculation_evidence_input",
        "calculation_dependency",
        "calculation_exclusion",
        "calculation_population",
        "calculation_population_filter",
        "atomic_claim",
        "claim_qualifier",
        "claim_support",
    ):
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_mutation
            BEFORE UPDATE OR DELETE ON evidence.{table}
            FOR EACH ROW
            EXECUTE FUNCTION evidence.reject_mutation()
            """
        )

    for table in (
        "calculation_record",
        "calculation_evidence_input",
        "calculation_dependency",
        "calculation_population",
        "calculation_population_filter",
    ):
        op.execute(
            f"""
            CREATE CONSTRAINT TRIGGER validate_{table}_aggregate
            AFTER INSERT ON evidence.{table}
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION evidence.validate_calculation_aggregate()
            """
        )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER reject_calculation_cycle
        AFTER INSERT ON evidence.calculation_dependency
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION evidence.reject_calculation_cycle()
        """
    )
    for table in ("atomic_claim", "claim_qualifier", "claim_support"):
        op.execute(
            f"""
            CREATE CONSTRAINT TRIGGER validate_{table}_aggregate
            AFTER INSERT ON evidence.{table}
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION evidence.validate_claim_aggregate()
            """
        )

    op.execute(
        """
        CREATE VIEW evidence.claim_eligible_evidence AS
        SELECT evidence_row.*
          FROM evidence.evidence_record AS evidence_row
          JOIN evidence.source_record AS source_row
            ON source_row.dataset_version = evidence_row.dataset_version
           AND source_row.source_id = evidence_row.source_id
          JOIN operations.dataset_version AS dataset
            ON dataset.dataset_version = evidence_row.dataset_version
         WHERE source_row.eligible_for_claim
           AND evidence_row.cutoff_status = 'eligible'
           AND (
               evidence_row.applicable_date IS NULL
               OR evidence_row.applicable_date <= dataset.cutoff_date
           )
           AND (
               evidence_row.published_at IS NULL
               OR (evidence_row.published_at AT TIME ZONE 'UTC')::date
                    <= dataset.cutoff_date
           )
           AND (
               evidence_row.available_at IS NULL
               OR (evidence_row.available_at AT TIME ZONE 'UTC')::date
                    <= dataset.cutoff_date
           )
           AND (
               evidence_row.vintage_date IS NULL
               OR evidence_row.vintage_date <= dataset.cutoff_date
           )
        """
    )

    for table in (
        "evidence_record",
        "evidence_observation_origin",
        "evidence_relation_origin",
        "evidence_document_origin",
        "calculation_record",
        "calculation_parameter",
        "calculation_evidence_input",
        "calculation_dependency",
        "calculation_exclusion",
        "calculation_population",
        "calculation_population_filter",
        "atomic_claim",
        "claim_qualifier",
        "claim_support",
    ):
        op.execute(f"ALTER TABLE evidence.{table} OWNER TO fa_migration")
    op.execute(
        "ALTER VIEW evidence.claim_eligible_evidence OWNER TO fa_migration"
    )
    for signature in (
        "reject_mutation()",
        "validate_cutoff_status()",
        "validate_evidence_origin()",
        "validate_calculation_aggregate()",
        "reject_calculation_cycle()",
        "validate_claim_aggregate()",
        "is_valid_tagged_value(jsonb)",
    ):
        op.execute(f"ALTER FUNCTION evidence.{signature} OWNER TO fa_migration")
        op.execute(
            f"REVOKE ALL ON FUNCTION evidence.{signature} "
            "FROM PUBLIC, fa_build, fa_runtime"
        )
    op.execute(
        "GRANT EXECUTE ON FUNCTION evidence.is_valid_tagged_value(jsonb) "
        "TO fa_build, fa_runtime"
    )
    op.execute(
        "REVOKE ALL ON evidence.claim_eligible_evidence "
        "FROM PUBLIC, fa_build, fa_runtime"
    )
    op.execute(
        "GRANT SELECT ON evidence.claim_eligible_evidence TO fa_build, fa_runtime"
    )
    op.execute(
        "REVOKE ALL ON evidence.evidence_record, "
        "evidence.evidence_observation_origin, "
        "evidence.evidence_relation_origin, evidence.evidence_document_origin "
        ", evidence.calculation_record, evidence.calculation_parameter, "
        "evidence.calculation_evidence_input, evidence.calculation_dependency, "
        "evidence.calculation_exclusion, evidence.calculation_population, "
        "evidence.calculation_population_filter, evidence.atomic_claim, "
        "evidence.claim_qualifier, evidence.claim_support "
        "FROM PUBLIC, fa_build, fa_runtime"
    )
    op.execute(
        "GRANT SELECT, INSERT ON evidence.evidence_record, "
        "evidence.evidence_observation_origin, "
        "evidence.evidence_relation_origin, evidence.evidence_document_origin "
        ", evidence.calculation_record, evidence.calculation_parameter, "
        "evidence.calculation_evidence_input, evidence.calculation_dependency, "
        "evidence.calculation_exclusion, evidence.calculation_population, "
        "evidence.calculation_population_filter, evidence.atomic_claim, "
        "evidence.claim_qualifier, evidence.claim_support "
        "TO fa_build, fa_runtime"
    )


def downgrade() -> None:
    op.execute(
        "DROP VIEW IF EXISTS evidence.claim_eligible_evidence"
    )
    for table in (
        "calculation_population_filter",
        "claim_support",
        "calculation_population",
        "calculation_exclusion",
        "calculation_evidence_input",
        "claim_qualifier",
        "calculation_parameter",
        "calculation_dependency",
        "atomic_claim",
        "calculation_record",
    ):
        op.execute(f"DROP TABLE IF EXISTS evidence.{table}")
    op.execute("DROP FUNCTION IF EXISTS evidence.validate_claim_aggregate()")
    op.execute("DROP FUNCTION IF EXISTS evidence.reject_calculation_cycle()")
    op.execute("DROP FUNCTION IF EXISTS evidence.validate_calculation_aggregate()")
    for table in (
        "evidence_record",
        "evidence_observation_origin",
        "evidence_relation_origin",
        "evidence_document_origin",
    ):
        op.execute(
            f"DROP TRIGGER IF EXISTS validate_{table}_origin ON evidence.{table}"
        )
        op.execute(
            f"DROP TRIGGER IF EXISTS reject_{table}_mutation ON evidence.{table}"
        )
    op.execute(
        "DROP TRIGGER IF EXISTS validate_cutoff_status "
        "ON evidence.evidence_record"
    )
    op.execute("DROP FUNCTION IF EXISTS evidence.validate_evidence_origin()")
    op.execute("DROP FUNCTION IF EXISTS evidence.validate_cutoff_status()")
    op.execute("DROP FUNCTION IF EXISTS evidence.reject_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_request_run_run_dataset', 'request_run', schema='operations', type_='unique')
    op.drop_table('evidence_document_origin', schema='evidence')
    op.drop_table('evidence_relation_origin', schema='evidence')
    op.drop_table('evidence_observation_origin', schema='evidence')
    op.drop_index('ix_evidence_record_subject_predicate_date', table_name='evidence_record', schema='evidence')
    op.drop_index('ix_evidence_record_source', table_name='evidence_record', schema='evidence')
    op.drop_index('ix_evidence_record_eligible_cutoff', table_name='evidence_record', schema='evidence', postgresql_where=sa.text("cutoff_status = 'eligible'"))
    op.drop_table('evidence_record', schema='evidence')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS evidence.is_valid_tagged_value(jsonb)")
