"""request artifacts

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-19 11:06:03.950267
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_unique_constraint(
        "uq_request_run_artifact_scope",
        "request_run",
        [
            "run_id",
            "request_key",
            "dataset_version",
            "cutoff_date",
            "schema_version",
        ],
        schema="operations",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_artifact',
    sa.Column('artifact_record_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contract_object_id', sa.Text(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('request_key', sa.CHAR(length=64), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('producer', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('canonical_payload', sa.Text(), nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.CHAR(length=64), nullable=False),
    sa.CheckConstraint("(model_id IS NULL) = (prompt_version IS NULL) AND (artifact_type = 'query_plan' AND model_id IS NOT NULL OR artifact_type = 'answer_plan' OR artifact_type NOT IN ('query_plan','answer_plan') AND model_id IS NULL)", name=op.f('ck_request_artifact_model_metadata')),
    sa.CheckConstraint("artifact_type IN ('request_context','query_plan','execution_graph','tool_result','evidence_bundle','verification_report','answer_plan','released_answer')", name=op.f('ck_request_artifact_artifact_type')),
    sa.CheckConstraint("payload_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_request_artifact_payload_hash')),
    sa.CheckConstraint("request_key ~ '^[0-9a-f]{64}$'", name=op.f('ck_request_artifact_request_key')),
    sa.CheckConstraint('octet_length(canonical_payload) > 0', name=op.f('ck_request_artifact_canonical_payload')),
    sa.ForeignKeyConstraint(['run_id', 'request_key', 'dataset_version', 'cutoff_date', 'schema_version'], ['operations.request_run.run_id', 'operations.request_run.request_key', 'operations.request_run.dataset_version', 'operations.request_run.cutoff_date', 'operations.request_run.schema_version'], name='fk_request_artifact_run_scope', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_record_id', name=op.f('pk_request_artifact')),
    sa.UniqueConstraint('artifact_record_id', 'run_id', 'dataset_version', name='uq_request_artifact_record_scope'),
    sa.UniqueConstraint('run_id', 'artifact_record_id', name='uq_request_artifact_run_record'),
    sa.UniqueConstraint('run_id', 'artifact_type', 'payload_hash', name='uq_request_artifact_retry'),
    schema='operations'
    )
    op.create_index('ix_request_artifact_dataset_cutoff', 'request_artifact', ['dataset_version', 'cutoff_date'], unique=False, schema='operations')
    op.create_index('ix_request_artifact_producer_schema', 'request_artifact', ['producer', 'schema_version'], unique=False, schema='operations')
    op.create_index('ix_request_artifact_request_created', 'request_artifact', ['request_key', 'run_id', 'artifact_type', 'created_at'], unique=False, schema='operations')
    op.create_index('uq_request_artifact_contract_object', 'request_artifact', ['run_id', 'artifact_type', 'contract_object_id'], unique=True, schema='operations', postgresql_where=sa.text('contract_object_id IS NOT NULL'))
    op.create_table('artifact_calculation_ref',
    sa.Column('artifact_record_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('calculation_id', sa.Text(), nullable=False),
    sa.Column('reference_role', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("btrim(reference_role) <> ''", name=op.f('ck_artifact_calculation_ref_reference_role')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_artifact_calculation_ref_ordinal')),
    sa.ForeignKeyConstraint(['artifact_record_id', 'run_id', 'dataset_version'], ['operations.request_artifact.artifact_record_id', 'operations.request_artifact.run_id', 'operations.request_artifact.dataset_version'], name='fk_artifact_calculation_ref_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'calculation_id'], ['evidence.calculation_record.run_id', 'evidence.calculation_record.dataset_version', 'evidence.calculation_record.calculation_id'], name='fk_artifact_calculation_ref_calculation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_record_id', 'reference_role', 'ordinal', name='pk_artifact_calculation_ref'),
    schema='operations'
    )
    op.create_index('ix_artifact_calculation_ref_target', 'artifact_calculation_ref', ['run_id', 'calculation_id'], unique=False, schema='operations')
    op.create_table('artifact_claim_ref',
    sa.Column('artifact_record_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('reference_role', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("btrim(reference_role) <> ''", name=op.f('ck_artifact_claim_ref_reference_role')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_artifact_claim_ref_ordinal')),
    sa.ForeignKeyConstraint(['artifact_record_id', 'run_id', 'dataset_version'], ['operations.request_artifact.artifact_record_id', 'operations.request_artifact.run_id', 'operations.request_artifact.dataset_version'], name='fk_artifact_claim_ref_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'dataset_version', 'claim_id'], ['evidence.atomic_claim.run_id', 'evidence.atomic_claim.dataset_version', 'evidence.atomic_claim.claim_id'], name='fk_artifact_claim_ref_claim', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_record_id', 'reference_role', 'ordinal', name='pk_artifact_claim_ref'),
    schema='operations'
    )
    op.create_index('ix_artifact_claim_ref_target', 'artifact_claim_ref', ['run_id', 'claim_id'], unique=False, schema='operations')
    op.create_table('artifact_evidence_ref',
    sa.Column('artifact_record_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('reference_role', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("btrim(reference_role) <> ''", name=op.f('ck_artifact_evidence_ref_reference_role')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_artifact_evidence_ref_ordinal')),
    sa.ForeignKeyConstraint(['artifact_record_id', 'run_id', 'dataset_version'], ['operations.request_artifact.artifact_record_id', 'operations.request_artifact.run_id', 'operations.request_artifact.dataset_version'], name='fk_artifact_evidence_ref_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version', 'evidence_id'], ['evidence.evidence_record.dataset_version', 'evidence.evidence_record.evidence_id'], name='fk_artifact_evidence_ref_evidence', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artifact_record_id', 'reference_role', 'ordinal', name='pk_artifact_evidence_ref'),
    schema='operations'
    )
    op.create_index('ix_artifact_evidence_ref_target', 'artifact_evidence_ref', ['dataset_version', 'evidence_id'], unique=False, schema='operations')
    op.add_column('request_run', sa.Column('final_verification_artifact_id', sa.UUID(), nullable=True), schema='operations')
    op.create_foreign_key('fk_request_run_final_verification_artifact', 'request_run', 'request_artifact', ['run_id', 'final_verification_artifact_id'], ['run_id', 'artifact_record_id'], source_schema='operations', referent_schema='operations', ondelete='RESTRICT', use_alter=True)
    op.create_check_constraint(op.f('ck_request_run_terminal_state'), 'request_run', "(finished_at IS NULL AND execution_outcome IS NULL AND verification_status IS NULL AND answer_disposition IS NULL AND http_status IS NULL AND terminal_failure_code IS NULL AND final_verification_artifact_id IS NULL) OR (finished_at IS NOT NULL AND execution_outcome IN ('completed','completed_with_failures') AND verification_status = 'pass' AND answer_disposition IS NOT NULL AND http_status = 200 AND terminal_failure_code IS NULL AND final_verification_artifact_id IS NOT NULL) OR (finished_at IS NOT NULL AND execution_outcome = 'failed' AND verification_status IS NULL AND answer_disposition IS NULL AND http_status BETWEEN 500 AND 599 AND terminal_failure_code IS NOT NULL AND btrim(terminal_failure_code) <> '' AND final_verification_artifact_id IS NULL)", schema='operations')
    # ### end Alembic commands ###
    op.execute(
        r"""
        CREATE FUNCTION operations.derive_request_artifact()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, operations, pg_temp
        AS $function$
        BEGIN
            NEW.payload_jsonb := NEW.canonical_payload::jsonb;
            IF pg_catalog.jsonb_typeof(NEW.payload_jsonb) IS DISTINCT FROM 'object'
            THEN
                RAISE EXCEPTION 'ARTIFACT_PAYLOAD_INVALID'
                    USING ERRCODE = '22023';
            END IF;

            NEW.payload_hash := pg_catalog.encode(
                public.digest(NEW.canonical_payload, 'sha256'), 'hex'
            );
            NEW.schema_version := NEW.payload_jsonb ->> 'schema_version';
            NEW.request_key := NEW.payload_jsonb ->> 'request_key';
            NEW.run_id := NEW.payload_jsonb ->> 'run_id';
            NEW.dataset_version := NEW.payload_jsonb ->> 'dataset_version';
            NEW.cutoff_date := (NEW.payload_jsonb ->> 'cutoff_date')::date;
            NEW.producer := NEW.payload_jsonb ->> 'producer';
            NEW.created_at := (NEW.payload_jsonb ->> 'created_at')::timestamptz;
            NEW.contract_object_id := CASE NEW.artifact_type
                WHEN 'execution_graph' THEN NEW.payload_jsonb ->> 'graph_id'
                WHEN 'tool_result' THEN NEW.payload_jsonb ->> 'task_id'
                WHEN 'evidence_bundle' THEN NEW.payload_jsonb ->> 'bundle_id'
                WHEN 'verification_report'
                    THEN NEW.payload_jsonb ->> 'verification_report_id'
                ELSE NULL
            END;

            IF NEW.schema_version IS NULL OR NEW.request_key IS NULL
               OR NEW.run_id IS NULL OR NEW.dataset_version IS NULL
               OR NEW.cutoff_date IS NULL OR NEW.producer IS NULL
               OR NEW.created_at IS NULL
            THEN
                RAISE EXCEPTION 'ARTIFACT_METADATA_INVALID'
                    USING ERRCODE = '22023';
            END IF;
            RETURN NEW;
        EXCEPTION
            WHEN invalid_text_representation OR datetime_field_overflow
                 OR invalid_datetime_format THEN
                RAISE EXCEPTION 'ARTIFACT_PAYLOAD_INVALID'
                    USING ERRCODE = '22023';
        END
        $function$
        """
    )
    op.execute(
        """
        CREATE TRIGGER derive_request_artifact
        BEFORE INSERT ON operations.request_artifact
        FOR EACH ROW
        EXECUTE FUNCTION operations.derive_request_artifact()
        """
    )
    for table in (
        "request_artifact",
        "artifact_evidence_ref",
        "artifact_calculation_ref",
        "artifact_claim_ref",
    ):
        op.execute(
            f"""
            CREATE TRIGGER reject_{table}_mutation
            BEFORE UPDATE OR DELETE ON operations.{table}
            FOR EACH ROW
            EXECUTE FUNCTION operations.reject_immutable_mutation()
            """
        )

    op.execute(
        r"""
        CREATE FUNCTION operations.append_request_artifact(
            p_artifact_type text,
            p_model_id text,
            p_prompt_version text,
            p_canonical_payload text
        ) RETURNS uuid
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, operations, pg_temp
        AS $function$
        DECLARE
            inserted_artifact operations.request_artifact%ROWTYPE;
            existing_artifact operations.request_artifact%ROWTYPE;
            candidate_jsonb jsonb;
            candidate_hash character(64);
            candidate_contract_id text;
        BEGIN
            INSERT INTO operations.request_artifact (
                artifact_type, model_id, prompt_version, canonical_payload
            ) VALUES (
                p_artifact_type, p_model_id, p_prompt_version, p_canonical_payload
            )
            ON CONFLICT DO NOTHING
            RETURNING * INTO inserted_artifact;

            IF NOT FOUND THEN
                candidate_jsonb := p_canonical_payload::jsonb;
                candidate_hash := pg_catalog.encode(
                    public.digest(p_canonical_payload, 'sha256'), 'hex'
                );
                candidate_contract_id := CASE p_artifact_type
                    WHEN 'execution_graph' THEN candidate_jsonb ->> 'graph_id'
                    WHEN 'tool_result' THEN candidate_jsonb ->> 'task_id'
                    WHEN 'evidence_bundle' THEN candidate_jsonb ->> 'bundle_id'
                    WHEN 'verification_report'
                        THEN candidate_jsonb ->> 'verification_report_id'
                    ELSE NULL
                END;
                SELECT artifact.*
                  INTO existing_artifact
                  FROM operations.request_artifact AS artifact
                 WHERE artifact.run_id = candidate_jsonb ->> 'run_id'
                   AND artifact.artifact_type = p_artifact_type
                   AND (
                       artifact.payload_hash = candidate_hash
                       OR (
                           candidate_contract_id IS NOT NULL
                           AND artifact.contract_object_id = candidate_contract_id
                       )
                   )
                 ORDER BY artifact.artifact_record_id
                 LIMIT 1;
                IF FOUND
                   AND existing_artifact.canonical_payload = p_canonical_payload
                   AND existing_artifact.model_id IS NOT DISTINCT FROM p_model_id
                   AND existing_artifact.prompt_version
                       IS NOT DISTINCT FROM p_prompt_version
                THEN
                    RETURN existing_artifact.artifact_record_id;
                END IF;
                RAISE EXCEPTION 'ARTIFACT_CONFLICT'
                    USING ERRCODE = 'P0001';
            END IF;

            IF inserted_artifact.artifact_type = 'query_plan' THEN
                INSERT INTO operations.request_subtask (
                    run_id, subtask_id, importance
                )
                SELECT inserted_artifact.run_id,
                       subtask.value ->> 'subtask_id',
                       subtask.value ->> 'importance'
                  FROM pg_catalog.jsonb_array_elements(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'subtasks', '[]'::jsonb
                      )
                  ) AS subtask(value);
            ELSIF inserted_artifact.artifact_type = 'tool_result' THEN
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'result',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'evidence_refs',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
            ELSIF inserted_artifact.artifact_type = 'evidence_bundle' THEN
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'included',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'evidence_ids',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'exclusion',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb
                              -> 'exclusion_evidence_ids',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       flattened.evidence_id,
                       'limitation',
                       pg_catalog.row_number() OVER (
                           ORDER BY flattened.limitation_ordinal,
                                    flattened.evidence_ordinal
                       ) - 1
                  FROM (
                      SELECT evidence.value AS evidence_id,
                             limitation.ordinality AS limitation_ordinal,
                             evidence.ordinality AS evidence_ordinal
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb -> 'limitations',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS limitation(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements_text(
                                COALESCE(
                                    limitation.value -> 'related_evidence_ids',
                                    '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS evidence(value, ordinality)
                  ) AS flattened;
                INSERT INTO operations.artifact_calculation_ref (
                    artifact_record_id, run_id, dataset_version, calculation_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'included',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'calculation_ids',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
                INSERT INTO operations.artifact_claim_ref (
                    artifact_record_id, run_id, dataset_version, claim_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'candidate',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'candidate_claim_ids',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
            ELSIF inserted_artifact.artifact_type = 'verification_report' THEN
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       flattened.evidence_id,
                       'claim_check',
                       pg_catalog.row_number() OVER (
                           ORDER BY flattened.check_ordinal,
                                    flattened.evidence_ordinal
                       ) - 1
                  FROM (
                      SELECT evidence.value AS evidence_id,
                             check_record.ordinality AS check_ordinal,
                             evidence.ordinality AS evidence_ordinal
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb -> 'claim_checks',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS check_record(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements_text(
                                COALESCE(
                                    check_record.value -> 'related_evidence_ids',
                                    '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS evidence(value, ordinality)
                  ) AS flattened;
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       flattened.evidence_id,
                       'calculation_check',
                       pg_catalog.row_number() OVER (
                           ORDER BY flattened.check_ordinal,
                                    flattened.evidence_ordinal
                       ) - 1
                  FROM (
                      SELECT evidence.value AS evidence_id,
                             check_record.ordinality AS check_ordinal,
                             evidence.ordinality AS evidence_ordinal
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb
                                    -> 'calculation_checks',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS check_record(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements_text(
                                COALESCE(
                                    check_record.value -> 'related_evidence_ids',
                                    '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS evidence(value, ordinality)
                  ) AS flattened;
                INSERT INTO operations.artifact_calculation_ref (
                    artifact_record_id, run_id, dataset_version, calculation_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       check_record.value ->> 'target_id',
                       'checked',
                       check_record.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'calculation_checks',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS check_record(value, ordinality)
                 WHERE check_record.value ->> 'target_type' = 'calculation';
                INSERT INTO operations.artifact_claim_ref (
                    artifact_record_id, run_id, dataset_version, claim_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       reference.value,
                       'releaseable',
                       reference.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements_text(
                      COALESCE(
                          inserted_artifact.payload_jsonb
                              -> 'releaseable_claim_ids',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS reference(value, ordinality);
                INSERT INTO operations.artifact_claim_ref (
                    artifact_record_id, run_id, dataset_version, claim_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       rejected.value ->> 'claim_id',
                       'rejected',
                       rejected.ordinality - 1
                  FROM pg_catalog.jsonb_array_elements(
                      COALESCE(
                          inserted_artifact.payload_jsonb -> 'rejected_claims',
                          '[]'::jsonb
                      )
                  ) WITH ORDINALITY AS rejected(value, ordinality);
            ELSIF inserted_artifact.artifact_type = 'answer_plan' THEN
                INSERT INTO operations.artifact_claim_ref (
                    artifact_record_id, run_id, dataset_version, claim_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       selected.claim_id,
                       'selected',
                       pg_catalog.row_number() OVER (
                           ORDER BY selected.block_ordinal,
                                    selected.row_group,
                                    selected.row_ordinal,
                                    selected.slot_ordinal
                       ) - 1
                  FROM (
                      SELECT block.ordinality AS block_ordinal,
                             0::bigint AS row_group,
                             0::bigint AS row_ordinal,
                             slot.ordinality AS slot_ordinal,
                             slot.value ->> 'claim_id' AS claim_id
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb -> 'blocks',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS block(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements(
                                COALESCE(
                                    block.value -> 'claim_slots', '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS slot(value, ordinality)
                      UNION ALL
                      SELECT block.ordinality AS block_ordinal,
                             1::bigint AS row_group,
                             row_record.ordinality AS row_ordinal,
                             cell.ordinality AS slot_ordinal,
                             cell.value ->> 'claim_id' AS claim_id
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb -> 'blocks',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS block(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements(
                                COALESCE(block.value -> 'rows', '[]'::jsonb)
                            ) WITH ORDINALITY AS row_record(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements(
                                COALESCE(
                                    row_record.value -> 'cells', '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS cell(value, ordinality)
                  ) AS selected;
            ELSIF inserted_artifact.artifact_type = 'released_answer' THEN
                INSERT INTO operations.artifact_claim_ref (
                    artifact_record_id, run_id, dataset_version, claim_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       flattened.claim_id,
                       'bound',
                       pg_catalog.row_number() OVER (
                           ORDER BY flattened.binding_ordinal,
                                    flattened.claim_ordinal
                       ) - 1
                  FROM (
                      SELECT claim.value AS claim_id,
                             binding.ordinality AS binding_ordinal,
                             claim.ordinality AS claim_ordinal
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb
                                    -> 'claim_bindings',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS binding(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements_text(
                                COALESCE(
                                    binding.value -> 'claim_ids', '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS claim(value, ordinality)
                  ) AS flattened;
                INSERT INTO operations.artifact_evidence_ref (
                    artifact_record_id, run_id, dataset_version, evidence_id,
                    reference_role, ordinal
                )
                SELECT inserted_artifact.artifact_record_id,
                       inserted_artifact.run_id,
                       inserted_artifact.dataset_version,
                       flattened.evidence_id,
                       'bound',
                       pg_catalog.row_number() OVER (
                           ORDER BY flattened.binding_ordinal,
                                    flattened.evidence_ordinal
                       ) - 1
                  FROM (
                      SELECT evidence.value AS evidence_id,
                             binding.ordinality AS binding_ordinal,
                             evidence.ordinality AS evidence_ordinal
                        FROM pg_catalog.jsonb_array_elements(
                            COALESCE(
                                inserted_artifact.payload_jsonb
                                    -> 'claim_bindings',
                                '[]'::jsonb
                            )
                        ) WITH ORDINALITY AS binding(value, ordinality)
                        CROSS JOIN LATERAL
                            pg_catalog.jsonb_array_elements_text(
                                COALESCE(
                                    binding.value -> 'evidence_ids', '[]'::jsonb
                                )
                            ) WITH ORDINALITY AS evidence(value, ordinality)
                  ) AS flattened;
            END IF;
            RETURN inserted_artifact.artifact_record_id;
        EXCEPTION
            WHEN unique_violation THEN
                RAISE EXCEPTION 'ARTIFACT_CONFLICT'
                    USING ERRCODE = 'P0001';
        END
        $function$
        """
    )
    op.execute(
        r"""
        CREATE FUNCTION operations.finish_request_run(
            p_run_id text,
            p_execution_outcome text,
            p_verification_status text,
            p_answer_disposition text,
            p_http_status smallint,
            p_final_verification_report_id text,
            p_terminal_failure_code text,
            p_finished_at timestamp with time zone
        ) RETURNS operations.request_run
        LANGUAGE plpgsql
        SECURITY DEFINER
        SET search_path = pg_catalog, operations, pg_temp
        AS $function$
        DECLARE
            request_record operations.request_run%ROWTYPE;
            report_record operations.request_artifact%ROWTYPE;
        BEGIN
            SELECT request.*
              INTO request_record
              FROM operations.request_run AS request
             WHERE request.run_id = p_run_id
             FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'REQUEST_RUN_NOT_FOUND'
                    USING ERRCODE = 'P0002';
            END IF;

            IF request_record.finished_at IS NOT NULL THEN
                IF request_record.execution_outcome = p_execution_outcome
                   AND request_record.verification_status
                       IS NOT DISTINCT FROM p_verification_status
                   AND request_record.answer_disposition
                       IS NOT DISTINCT FROM p_answer_disposition
                   AND request_record.http_status = p_http_status
                   AND request_record.terminal_failure_code
                       IS NOT DISTINCT FROM p_terminal_failure_code
                   AND request_record.finished_at = p_finished_at
                   AND (
                       p_final_verification_report_id IS NULL
                       AND request_record.final_verification_artifact_id IS NULL
                       OR EXISTS (
                           SELECT 1
                             FROM operations.request_artifact AS artifact
                            WHERE artifact.run_id = p_run_id
                              AND artifact.artifact_record_id =
                                  request_record.final_verification_artifact_id
                              AND artifact.artifact_type = 'verification_report'
                              AND artifact.contract_object_id =
                                  p_final_verification_report_id
                       )
                   )
                THEN
                    RETURN request_record;
                END IF;
                RAISE EXCEPTION 'REQUEST_RUN_CONFLICT'
                    USING ERRCODE = 'P0001';
            END IF;

            IF p_http_status = 200 THEN
                IF p_execution_outcome NOT IN (
                       'completed', 'completed_with_failures'
                   )
                   OR p_verification_status IS DISTINCT FROM 'pass'
                   OR p_answer_disposition IS NULL
                   OR p_final_verification_report_id IS NULL
                   OR p_terminal_failure_code IS NOT NULL
                THEN
                    RAISE EXCEPTION 'INVALID_TERMINAL_STATE'
                        USING ERRCODE = 'P0001';
                END IF;
                SELECT artifact.*
                  INTO report_record
                  FROM operations.request_artifact AS artifact
                 WHERE artifact.run_id = p_run_id
                   AND artifact.artifact_type = 'verification_report'
                   AND artifact.contract_object_id =
                       p_final_verification_report_id
                 FOR SHARE;
                IF NOT FOUND
                   OR report_record.payload_jsonb ->> 'verification_status'
                       IS DISTINCT FROM 'pass'
                   OR report_record.payload_jsonb
                       ->> 'recommended_answer_disposition'
                       IS DISTINCT FROM p_answer_disposition
                THEN
                    RAISE EXCEPTION 'FINAL_VERIFICATION_ARTIFACT_INVALID'
                        USING ERRCODE = 'P0001';
                END IF;
            ELSIF p_http_status BETWEEN 500 AND 599 THEN
                IF p_execution_outcome IS DISTINCT FROM 'failed'
                   OR p_verification_status IS NOT NULL
                   OR p_answer_disposition IS NOT NULL
                   OR p_final_verification_report_id IS NOT NULL
                   OR p_terminal_failure_code IS NULL
                   OR pg_catalog.btrim(p_terminal_failure_code) = ''
                THEN
                    RAISE EXCEPTION 'INVALID_TERMINAL_STATE'
                        USING ERRCODE = 'P0001';
                END IF;
            ELSE
                RAISE EXCEPTION 'INVALID_TERMINAL_STATE'
                    USING ERRCODE = 'P0001';
            END IF;

            UPDATE operations.request_run
               SET finished_at = p_finished_at,
                   execution_outcome = p_execution_outcome,
                   verification_status = p_verification_status,
                   answer_disposition = p_answer_disposition,
                   http_status = p_http_status,
                   final_verification_artifact_id =
                       report_record.artifact_record_id,
                   terminal_failure_code = p_terminal_failure_code
             WHERE run_id = p_run_id
            RETURNING * INTO request_record;
            RETURN request_record;
        END
        $function$
        """
    )

    for table in (
        "request_artifact",
        "artifact_evidence_ref",
        "artifact_calculation_ref",
        "artifact_claim_ref",
    ):
        op.execute(f"ALTER TABLE operations.{table} OWNER TO fa_migration")
    for signature in (
        "derive_request_artifact()",
        "append_request_artifact(text,text,text,text)",
        (
            "finish_request_run(text,text,text,text,smallint,text,text,"
            "timestamp with time zone)"
        ),
    ):
        op.execute(f"ALTER FUNCTION operations.{signature} OWNER TO fa_migration")
        op.execute(
            f"REVOKE ALL ON FUNCTION operations.{signature} "
            "FROM PUBLIC, fa_build, fa_runtime"
        )
    op.execute(
        "REVOKE ALL ON operations.request_artifact, "
        "operations.artifact_evidence_ref, "
        "operations.artifact_calculation_ref, operations.artifact_claim_ref "
        "FROM PUBLIC, fa_build, fa_runtime"
    )
    op.execute(
        "GRANT SELECT ON operations.request_artifact, "
        "operations.artifact_evidence_ref, "
        "operations.artifact_calculation_ref, operations.artifact_claim_ref "
        "TO fa_runtime"
    )
    op.execute(
        "REVOKE INSERT ON operations.request_subtask FROM fa_runtime"
    )
    op.execute(
        "GRANT EXECUTE ON FUNCTION "
        "operations.append_request_artifact(text,text,text,text) TO fa_runtime"
    )
    op.execute(
        "GRANT EXECUTE ON FUNCTION operations.finish_request_run("
        "text,text,text,text,smallint,text,text,timestamp with time zone) "
        "TO fa_runtime"
    )


def downgrade() -> None:
    # Removing the final VerificationReport also removes the required evidence
    # for a semantic terminal state. Reopen only those runs before dropping it.
    op.execute(
        """
        UPDATE operations.request_run
           SET finished_at = NULL,
               execution_outcome = NULL,
               verification_status = NULL,
               answer_disposition = NULL,
               http_status = NULL,
               terminal_failure_code = NULL,
               final_verification_artifact_id = NULL
         WHERE final_verification_artifact_id IS NOT NULL
        """
    )
    op.execute(
        "DROP TRIGGER IF EXISTS derive_request_artifact "
        "ON operations.request_artifact"
    )
    for table in (
        "request_artifact",
        "artifact_evidence_ref",
        "artifact_calculation_ref",
        "artifact_claim_ref",
    ):
        op.execute(
            f"DROP TRIGGER IF EXISTS reject_{table}_mutation "
            f"ON operations.{table}"
        )
    op.execute(
        "DROP FUNCTION IF EXISTS operations.finish_request_run("
        "text,text,text,text,smallint,text,text,timestamp with time zone)"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS "
        "operations.append_request_artifact(text,text,text,text)"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS operations.derive_request_artifact()"
    )
    op.execute(
        "GRANT INSERT ON operations.request_subtask TO fa_runtime"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_request_run_terminal_state'), 'request_run', schema='operations', type_='check')
    op.drop_constraint('fk_request_run_final_verification_artifact', 'request_run', schema='operations', type_='foreignkey')
    op.drop_column('request_run', 'final_verification_artifact_id', schema='operations')
    op.drop_index('ix_artifact_evidence_ref_target', table_name='artifact_evidence_ref', schema='operations')
    op.drop_table('artifact_evidence_ref', schema='operations')
    op.drop_index('ix_artifact_claim_ref_target', table_name='artifact_claim_ref', schema='operations')
    op.drop_table('artifact_claim_ref', schema='operations')
    op.drop_index('ix_artifact_calculation_ref_target', table_name='artifact_calculation_ref', schema='operations')
    op.drop_table('artifact_calculation_ref', schema='operations')
    op.drop_index('uq_request_artifact_contract_object', table_name='request_artifact', schema='operations', postgresql_where=sa.text('contract_object_id IS NOT NULL'))
    op.drop_index('ix_request_artifact_request_created', table_name='request_artifact', schema='operations')
    op.drop_index('ix_request_artifact_producer_schema', table_name='request_artifact', schema='operations')
    op.drop_index('ix_request_artifact_dataset_cutoff', table_name='request_artifact', schema='operations')
    op.drop_table('request_artifact', schema='operations')
    op.drop_constraint('uq_request_run_artifact_scope', 'request_run', schema='operations', type_='unique')
    # ### end Alembic commands ###
