from importlib import import_module
from typing import TYPE_CHECKING, Any

from .base import (
    CONTRACT_SCHEMA_VERSION,
    SNAPSHOT_CUTOFF,
    ContractModel,
    Identifier,
    RuntimeArtifact,
    Sha256Hex,
    UtcDateTime,
)
from .answer import (
    AnswerBlock,
    AnswerPlan,
    AnswerRow,
    ClaimBinding,
    ClaimSlot,
    DispositionReason,
    EvaluationApiResponse,
    RejectedClaim,
    ReleasedAnswer,
    RepairAction,
    SubtaskCoverage,
    VerificationReport,
)
from .canonical import (
    build_request_key,
    canonical_json_bytes,
    canonical_sha256,
    normalize_question,
)
from .compatibility import (
    validate_execution_graph_compatibility,
    validate_tool_result_compatibility,
)
from .execution import (
    BindingTypeInput,
    BindingValue,
    Exclusion,
    ExecutionGraph,
    ExecutionTask,
    NamedValue,
    ResultField,
    ResultRow,
    ResultWarning,
    ToolResult,
)
from .evidence import (
    AppliedDefault,
    AtomicClaim,
    CalculationParameter,
    CalculationRecord,
    CheckResult,
    ClaimQualifier,
    ClaimSupport,
    EvidenceBundle,
    EvidenceRecord,
    Limitation,
    MissingData,
    PopulationDefinition,
    SourceLocator,
    SourceRecord,
)
from .enums import (
    AnswerDisposition,
    BlockType,
    CalculationType,
    Capability,
    Cardinality,
    CheckStatus,
    CheckTargetType,
    ClaimType,
    CutoffStatus,
    EntityResolutionStatus,
    EvidenceKind,
    ExecutionOutcome,
    InitialAnswerability,
    InteractionMode,
    IntentType,
    ProductFamily,
    ReferenceMentionType,
    ReferenceTargetKind,
    Repairability,
    ResultShape,
    ResultType,
    SubtaskImportance,
    SupportKind,
    ToolStatus,
    VerificationStatus,
)
from .query import (
    AmbiguityDecision,
    BindingSpec,
    DependencyEdge,
    EntityResolutionRequest,
    FilterSpec,
    MetricSpec,
    OperationSpec,
    QueryPlan,
    ResolvedReference,
    Subtask,
)
from .request import (
    NamedEntityMention,
    ReferenceMention,
    RequestContext,
    Segment,
)
from .values import (
    BooleanValue,
    ContractPrimitive,
    ContractValue,
    DateTimeValue,
    DateValue,
    DecimalValue,
    IntegerValue,
    NullValue,
    ScalarPrimitive,
    ScalarValue,
    StringValue,
    TupleValue,
    decode_contract_value,
    encode_contract_value,
)

if TYPE_CHECKING:
    from financial_agent.intent.query_contracts import ResolvedQueryContractSetV2
    from financial_agent.planning.logical_query import LogicalQueryPlanV2


_LAZY_EXPORTS = {
    "ResolvedQueryContractSetV2": (
        "financial_agent.intent.query_contracts",
        "ResolvedQueryContractSetV2",
    ),
    "LogicalQueryPlanV2": (
        "financial_agent.planning.logical_query",
        "LogicalQueryPlanV2",
    ),
}


def __getattr__(name: str) -> Any:
    """Load cross-layer V2 exports without creating package import cycles."""
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted((*globals(), *_LAZY_EXPORTS))

__all__ = [
    "CONTRACT_SCHEMA_VERSION",
    "SNAPSHOT_CUTOFF",
    "ContractModel",
    "ContractValue",
    "Identifier",
    "RuntimeArtifact",
    "ScalarValue",
    "Sha256Hex",
    "UtcDateTime",
    "AnswerBlock",
    "AnswerPlan",
    "AnswerRow",
    "ClaimBinding",
    "ClaimSlot",
    "DispositionReason",
    "EvaluationApiResponse",
    "RejectedClaim",
    "ReleasedAnswer",
    "RepairAction",
    "SubtaskCoverage",
    "VerificationReport",
    "AmbiguityDecision",
    "BindingSpec",
    "DependencyEdge",
    "EntityResolutionRequest",
    "FilterSpec",
    "MetricSpec",
    "OperationSpec",
    "QueryPlan",
    "ResolvedReference",
    "Subtask",
    "NamedEntityMention",
    "ReferenceMention",
    "RequestContext",
    "Segment",
    "AnswerDisposition",
    "BlockType",
    "CalculationType",
    "Capability",
    "Cardinality",
    "CheckStatus",
    "CheckTargetType",
    "ClaimType",
    "CutoffStatus",
    "EntityResolutionStatus",
    "EvidenceKind",
    "ExecutionOutcome",
    "InitialAnswerability",
    "InteractionMode",
    "IntentType",
    "ProductFamily",
    "ReferenceMentionType",
    "ReferenceTargetKind",
    "Repairability",
    "ResultShape",
    "ResultType",
    "SubtaskImportance",
    "SupportKind",
    "ToolStatus",
    "VerificationStatus",
    "build_request_key",
    "canonical_json_bytes",
    "canonical_sha256",
    "normalize_question",
    "validate_execution_graph_compatibility",
    "validate_tool_result_compatibility",
    "BindingValue",
    "BindingTypeInput",
    "Exclusion",
    "ExecutionGraph",
    "ExecutionTask",
    "NamedValue",
    "ResultField",
    "ResultRow",
    "ResultWarning",
    "ToolResult",
    "AppliedDefault",
    "AtomicClaim",
    "CalculationParameter",
    "CalculationRecord",
    "CheckResult",
    "ClaimQualifier",
    "ClaimSupport",
    "EvidenceBundle",
    "EvidenceRecord",
    "Limitation",
    "MissingData",
    "PopulationDefinition",
    "SourceLocator",
    "SourceRecord",
    "BooleanValue",
    "ContractPrimitive",
    "DateTimeValue",
    "DateValue",
    "DecimalValue",
    "IntegerValue",
    "NullValue",
    "ScalarPrimitive",
    "StringValue",
    "TupleValue",
    "decode_contract_value",
    "encode_contract_value",
    "ResolvedQueryContractSetV2",
    "LogicalQueryPlanV2",
]
